#!/bin/sh
#
# Copyright (c) 2021 Keira Dueck <sylae@calref.net>
# Use of this source code is governed by the MIT license, which
# can be found in the LICENSE file.
#

until php bot.php; do
  echo "Process ended with exit code $?. Restarting..."
  sleep 1
done
echo "Process ended with exit code $?. Not restarting."
