#!/bin/sh -x

#
# Copyright (c) 2021 Keira Dueck <sylae@calref.net>
# Use of this source code is governed by the MIT license, which
# can be found in the LICENSE file.
#

git pull --recurse-submodules
composer install --no-progress --ignore-platform-reqs
